### ISSUE TITLE
No strong named version available

### ISSUE THREAD

**Issue by thomas-boll** [advancedrei/Zlib.Portable#1]
Hello,

can a strong named version be provided?

Because if someone (like me) needs to strong name his own assemblies, the referenced assemblies also need to be strong named.

Thanks.

EDIT: also see my pull request under https://github.com/advancedrei/Zlib.Portable/pull/2

**Comment by Atrejoe** [comment]
Another project trying to get its assemblies signed depends on this component to be signed too, see: https://code.google.com/p/google-api-dotnet-client/issues/detail?id=238

**Comment by LindaLawton** [comment]
Any chance on getting this signed?   Needed for this https://github.com/google/google-api-dotnet-client/issues/238

**Comment by LindaLawton** [comment]
We tested the beta version you released all looks good. do you have an eta on a release?

**Comment by advancedrei** [comment]
The strong-named version has now been officially released. Thanks for your feedback!
