### ISSUE TITLE
The Portable part isn't really true, but very easy to fix (by deleting 4 lines of code)

### ISSUE THREAD

**Issue by ddotlic** [advancedrei/Zlib.Portable#6]
Hi,

turns out that when one builds a PCL the symbol SILVERLIGHT isn't defined, so the code with `#if SILVERLIGHT` directives does not get compiled.

Turns out that there is one place which does use this directive, it's the one in `GZipStream` class (gets executed as part of static constructor), reproduced here:

		#if SILVERLIGHT || NETCF
		        internal static readonly System.Text.Encoding iso8859dash1 = new Ionic.Encoding.Iso8859Dash1Encoding();
		#else
		        internal static readonly System.Text.Encoding iso8859dash1 = System.Text.Encoding.GetEncoding("iso-8859-1");
		#endif

Seeing how neither `SILVERLIGHT` nor `NETCF` are defined for PCL builds, only the `#else` branch will be used and encoding which doesn't exist in Silverlight (and presumably compact framework too) will be baked in the final assembly, which will crash the static constructor of `GZipStream`.

This should be easy to fix by simply never using platform's built-in `Encoding` but always using `Iso8859Dash1Encoding` especially since the encoding here is just a no-op encoding, there's no question of performance or correctness.

So could you please simply remove the `#if/#else/#endif` and just use `Iso8859Dash1Encoding` which should work on all platforms? I've checked and there are no other places in the code which reference `SILVERLIGHT`, so this should be the only thing preventing this library from working on Silverlight.

After the fix, would you be so kind to push the new version to NuGet?

Thanks.

**Comment by advancedrei** [comment]
This has been fixed in the next release and will be pushed to NuGet shortly.

**Comment by ddotlic** [comment]
Great! We ended up using a different (bloated) library in the meantime but I'll make sure to go back to this one shortly. Thanks.
